/**
 * Autonomous Workflow Configuration
 * Defines the complete workflow for autonomous project completion
 */

import { Task } from './orchestrator3';

/**
 * Generate comprehensive task list for 100% completion
 */
export function generateAutonomousWorkflow(): Task[] {
  return [
    // PHASE 1: Critical Build Fixes (Priority: CRITICAL)
    {
      id: 'TASK-001',
      title: 'Install missing npm dependencies',
      description: 'Install @vercel/analytics, jsonwebtoken, googleapis and their types',
      status: 'pending',
      priority: 'critical',
      estimatedMinutes: 2,
      createdAt: new Date(),
    },
    {
      id: 'TASK-002',
      title: 'Fix next.config.js configuration',
      description: 'Update serverExternalPackages to correct Next.js 14 syntax',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-001'],
      estimatedMinutes: 1,
      createdAt: new Date(),
    },
    {
      id: 'TASK-003',
      title: 'Create PulseInbox component stub',
      description: 'Create minimal PulseInbox component or comment out imports',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-001'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },
    {
      id: 'TASK-004',
      title: 'Run production build test',
      description: 'Execute npm run build and verify no errors',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-001', 'TASK-002', 'TASK-003'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },

    // PHASE 2: Production Database Setup (Priority: CRITICAL)
    {
      id: 'TASK-005',
      title: 'Create production Supabase project',
      description: 'Set up new Supabase project at supabase.com for production use',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-004'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-006',
      title: 'Apply database migrations to production',
      description: 'Run npx supabase db push to apply all migrations',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-005'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },
    {
      id: 'TASK-007',
      title: 'Configure Row-Level Security policies',
      description: 'Enable RLS and create security policies for all tables',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-006'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },
    {
      id: 'TASK-008',
      title: 'Verify database connection and tables',
      description: 'Test connection and verify all required tables exist',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-007'],
      estimatedMinutes: 3,
      createdAt: new Date(),
    },

    // PHASE 3: Authentication Setup (Priority: CRITICAL)
    {
      id: 'TASK-009',
      title: 'Create production Clerk application',
      description: 'Set up Clerk app at clerk.com for production auth',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-004'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-010',
      title: 'Configure Clerk domains',
      description: 'Add dealershipai.com and dash.dealershipai.com to Clerk',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-009'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },
    {
      id: 'TASK-011',
      title: 'Set up Clerk webhooks',
      description: 'Configure user.created and user.updated webhooks',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-010'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },

    // PHASE 4: Vercel Deployment (Priority: HIGH)
    {
      id: 'TASK-012',
      title: 'Link project to Vercel',
      description: 'Run vercel link to connect local project',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-004'],
      estimatedMinutes: 2,
      createdAt: new Date(),
    },
    {
      id: 'TASK-013',
      title: 'Configure production environment variables',
      description: 'Set all required env vars in Vercel (Supabase, Clerk, OpenAI)',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-008', 'TASK-010', 'TASK-012'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },
    {
      id: 'TASK-014',
      title: 'Deploy to Vercel preview',
      description: 'Run vercel command to deploy preview',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-013'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-015',
      title: 'Test preview deployment',
      description: 'Verify auth, dashboard, and API endpoints work on preview',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-014'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },
    {
      id: 'TASK-016',
      title: 'Deploy to production',
      description: 'Run vercel --prod to deploy to production',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-015'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },

    // PHASE 5: Domain Configuration (Priority: HIGH)
    {
      id: 'TASK-017',
      title: 'Configure api.dealershipai.com domain',
      description: 'Add api.dealershipai.com domain to Vercel project',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-016'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },
    {
      id: 'TASK-018',
      title: 'Update DNS records',
      description: 'Point api.dealershipai.com to Vercel with CNAME/A records',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-017'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-019',
      title: 'Verify SSL certificate',
      description: 'Ensure HTTPS is working on api.dealershipai.com',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-018'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },

    // PHASE 6: Monitoring & Analytics (Priority: MEDIUM)
    {
      id: 'TASK-020',
      title: 'Set up Sentry error tracking',
      description: 'Create Sentry project and configure DSN',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-016'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-021',
      title: 'Enable Vercel Analytics',
      description: 'Activate Vercel Analytics for performance monitoring',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-016'],
      estimatedMinutes: 3,
      createdAt: new Date(),
    },
    {
      id: 'TASK-022',
      title: 'Configure log drains',
      description: 'Set up log forwarding from Vercel to monitoring service',
      status: 'pending',
      priority: 'low',
      dependencies: ['TASK-021'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },

    // PHASE 7: API Endpoints (Priority: HIGH)
    {
      id: 'TASK-023',
      title: 'Deploy Orchestrator 3.0 API endpoints',
      description: 'Verify /api/orchestrator/v3/* endpoints are live',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-016'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },
    {
      id: 'TASK-024',
      title: 'Test autonomous orchestrator via API',
      description: 'POST to /api/orchestrator/v3/deploy and verify operation',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-023'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-025',
      title: 'Verify all health endpoints',
      description: 'Test /api/health, /api/orchestrator/status, etc.',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-023'],
      estimatedMinutes: 5,
      createdAt: new Date(),
    },

    // PHASE 8: Performance Optimization (Priority: MEDIUM)
    {
      id: 'TASK-026',
      title: 'Analyze bundle size',
      description: 'Run build analysis and identify optimization opportunities',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-016'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-027',
      title: 'Optimize images and assets',
      description: 'Convert images to WebP/AVIF and configure Next.js Image',
      status: 'pending',
      priority: 'low',
      dependencies: ['TASK-026'],
      estimatedMinutes: 20,
      createdAt: new Date(),
    },
    {
      id: 'TASK-028',
      title: 'Enable caching and ISR',
      description: 'Configure revalidation times for ISR pages',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-016'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-029',
      title: 'Add database indexes',
      description: 'Create performance indexes for frequently queried tables',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-008'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },

    // PHASE 9: Security Hardening (Priority: HIGH)
    {
      id: 'TASK-030',
      title: 'Review and update CSP headers',
      description: 'Ensure Content-Security-Policy is properly configured',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-016'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-031',
      title: 'Enable rate limiting',
      description: 'Set up API rate limiting with Vercel Edge Config or Upstash',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-023'],
      estimatedMinutes: 20,
      createdAt: new Date(),
    },
    {
      id: 'TASK-032',
      title: 'Run security audit',
      description: 'Execute npm audit and fix critical vulnerabilities',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-004'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-033',
      title: 'Verify API authentication',
      description: 'Test that all API routes properly check auth',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-025'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },

    // PHASE 10: Testing & Validation (Priority: CRITICAL)
    {
      id: 'TASK-034',
      title: 'Run smoke tests on production',
      description: 'Test auth flow, dashboard load, API endpoints',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-019'],
      estimatedMinutes: 20,
      createdAt: new Date(),
    },
    {
      id: 'TASK-035',
      title: 'Test mobile responsiveness',
      description: 'Verify dashboard works on mobile devices',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-034'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
    {
      id: 'TASK-036',
      title: 'Run load testing',
      description: 'Execute load tests with Artillery or k6',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-034'],
      estimatedMinutes: 15,
      createdAt: new Date(),
    },
    {
      id: 'TASK-037',
      title: 'Verify all success criteria',
      description: 'Check that all deployment success criteria are met',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-034', 'TASK-035'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },

    // PHASE 11: Documentation (Priority: MEDIUM)
    {
      id: 'TASK-038',
      title: 'Update deployment documentation',
      description: 'Document final deployment configuration and procedures',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-037'],
      estimatedMinutes: 30,
      createdAt: new Date(),
    },
    {
      id: 'TASK-039',
      title: 'Create API documentation',
      description: 'Generate OpenAPI/Swagger docs for all endpoints',
      status: 'pending',
      priority: 'low',
      dependencies: ['TASK-025'],
      estimatedMinutes: 45,
      createdAt: new Date(),
    },
    {
      id: 'TASK-040',
      title: 'Write deployment runbook',
      description: 'Create step-by-step runbook for future deployments',
      status: 'pending',
      priority: 'medium',
      dependencies: ['TASK-037'],
      estimatedMinutes: 30,
      createdAt: new Date(),
    },

    // FINAL: Celebration and Handoff
    {
      id: 'TASK-041',
      title: 'Generate completion report',
      description: 'Create comprehensive report of all completed work',
      status: 'pending',
      priority: 'high',
      dependencies: ['TASK-037'],
      estimatedMinutes: 20,
      createdAt: new Date(),
    },
    {
      id: 'TASK-042',
      title: 'Deploy orchestrator to api.dealershipai.com',
      description: 'Final deployment of autonomous orchestrator to production URL',
      status: 'pending',
      priority: 'critical',
      dependencies: ['TASK-019', 'TASK-024', 'TASK-037'],
      estimatedMinutes: 10,
      createdAt: new Date(),
    },
  ];
}

/**
 * Get workflow statistics
 */
export function getWorkflowStats(tasks: Task[]) {
  const byStatus = {
    pending: tasks.filter(t => t.status === 'pending').length,
    in_progress: tasks.filter(t => t.status === 'in_progress').length,
    completed: tasks.filter(t => t.status === 'completed').length,
    failed: tasks.filter(t => t.status === 'failed').length,
    blocked: tasks.filter(t => t.status === 'blocked').length,
  };

  const byPriority = {
    critical: tasks.filter(t => t.priority === 'critical').length,
    high: tasks.filter(t => t.priority === 'high').length,
    medium: tasks.filter(t => t.priority === 'medium').length,
    low: tasks.filter(t => t.priority === 'low').length,
  };

  const totalEstimatedMinutes = tasks.reduce((sum, t) => sum + (t.estimatedMinutes || 0), 0);

  return {
    total: tasks.length,
    byStatus,
    byPriority,
    totalEstimatedMinutes,
    totalEstimatedHours: Math.round(totalEstimatedMinutes / 60 * 10) / 10,
  };
}
