project_id = "gzlgfghpkbqlhgfozjkb"
[api]
port = 54321
schemas = ["public"]
[db]
shadow_port = 54322
[studio]
port = 54323
[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["http://localhost:3000"]
[functions]
