#!/bin/bash

echo "🌐 Configuring DealershipAI Domains and Services"
echo "================================================"
echo ""

echo "📋 Current Project: dealership-ai-dashboard"
echo "🔗 Vercel Project URL: https://vercel.com/brian-kramers-projects/dealership-ai-dashboard"
echo ""

echo "🎯 Target Domains to Configure:"
echo "• marketing.dealershipai.com (Landing Page)"
echo "• dash.dealershipai.com (Dashboard)"
echo "• main.dealershipai.com (Main Page)"
echo ""

echo "🔧 Configuration Steps:"
echo ""

echo "1. Vercel Domain Configuration:"
echo "   Go to: https://vercel.com/brian-kramers-projects/dealershipai-dashboard/settings/domains"
echo "   Add domains:"
echo "   - marketing.dealershipai.com"
echo "   - dash.dealershipai.com" 
echo "   - main.dealershipai.com"
echo ""

echo "2. DNS Configuration:"
echo "   Point these domains to Vercel:"
echo "   - A record: @ → 76.76.19.61"
echo "   - CNAME: www → cname.vercel-dns.com"
echo ""

echo "3. Environment Variables:"
echo "   Update .env.local with:"
echo "   NEXT_PUBLIC_APP_URL=https://marketing.dealershipai.com"
echo "   NEXT_PUBLIC_DASHBOARD_URL=https://dash.dealershipai.com"
echo "   NEXTAUTH_URL=https://marketing.dealershipai.com"
echo ""

echo "4. Supabase Configuration:"
echo "   Update Supabase project settings:"
echo "   - Site URL: https://marketing.dealershipai.com"
echo "   - Redirect URLs:"
echo "     - https://marketing.dealershipai.com/auth/callback"
echo "     - https://dash.dealershipai.com/auth/callback"
echo "     - https://main.dealershipai.com/auth/callback"
echo ""

echo "5. GitHub Repository:"
echo "   Ensure repository is connected:"
echo "   - Repository: brian-kramers-projects/dealership-ai-dashboard"
echo "   - Auto-deploy: Enabled"
echo "   - Branch: main"
echo ""

echo "🚀 Ready to Configure Domains!"
echo "=============================="
echo ""
echo "Next steps:"
echo "1. Run: vercel link (to connect project)"
echo "2. Add domains in Vercel dashboard"
echo "3. Update DNS records"
echo "4. Deploy with new domains"
echo ""
