app = 'dealershipai-dtri-ada'
primary_region = 'iad'

[build]
  image = 'python:3.11-slim'

[env]
  PORT = '8080'
  PYTHONPATH = '/app'
  LOG_LEVEL = 'INFO'

[[services]]
  internal_port = 8080
  protocol = 'tcp'
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  max_machines_running = 3

  [[services.ports]]
    handlers = ['http']
    port = 80

  [[services.ports]]
    handlers = ['tls', 'http']
    port = 443

  [services.concurrency]
    type = 'connections'
    hard_limit = 1000
    soft_limit = 800

[metrics]
  port = 9091
  path = '/metrics'
