#!/bin/bash

echo "🔐 Getting Vercel Access for DealershipAI Demo"
echo "=============================================="
echo ""

echo "📋 Current Deployment:"
echo "URL: https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app"
echo "Status: ✅ Live with authentication protection"
echo ""

echo "🔑 To Access the Deployment:"
echo ""
echo "Method 1: Vercel Dashboard"
echo "1. Go to: https://vercel.com/brian-kramers-projects/dealershipai-dashboard"
echo "2. Click 'Settings' → 'Security'"
echo "3. Find 'Protection Bypass Token'"
echo "4. Copy the token"
echo ""

echo "Method 2: Vercel CLI"
echo "1. Run: vercel --token YOUR_TOKEN"
echo "2. Or use bypass URL:"
echo "   https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo ""

echo "🎯 Demo URLs (with bypass token):"
echo ""
echo "Marketing Page:"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/marketing?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo ""
echo "Main Page:"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/main?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo ""
echo "Competitive Advantage APIs:"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/api/ai/recommendations?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/api/competitors/intelligence?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/api/alerts/prioritization?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo "https://dealershipai-dashboard-7nzr80nrx-brian-kramers-projects.vercel.app/api/ai/predictive-optimization?x-vercel-set-bypass-cookie=true&x-vercel-protection-bypass=YOUR_TOKEN"
echo ""

echo "🏆 Ready to Demo Competitive Advantage Features!"
echo "================================================"
echo ""
echo "✅ AI-Powered Recommendations Engine"
echo "✅ Advanced Competitor Intelligence"
echo "✅ Smart Alert Prioritization"
echo "✅ Predictive Optimization Engine"
echo "✅ Enhanced Opportunity Calculator"
echo "✅ Competitive Advantage Dashboard"
echo ""
echo "💰 Target: Close $499 deals with market differentiation!"
echo ""
echo "📖 See DEAL-CLOSING-DEMO-GUIDE.md for complete demo script"
