#!/bin/bash

# DealershipAI - Setup Clerk Environment Variables
# This script helps you add Clerk keys to Vercel

echo "🔑 DealershipAI - Clerk Setup"
echo "============================="
echo ""
echo "📋 Production URL:"
echo "https://dealership-ai-dashboard-brian-kramer-dealershipai.vercel.app"
echo ""
echo "🌐 Vercel Dashboard:"
echo "https://vercel.com/brian-kramer-dealershipai/dealership-ai-dashboard/settings/environment-variables"
echo ""
echo ""
echo "📝 STEP 1: Get Clerk Keys"
echo "-------------------------"
echo "1. Go to: https://dashboard.clerk.com"
echo "2. Sign in to your account"
echo "3. Select 'dealership-ai-dashboard' app"
echo "4. Go to 'API Keys' section"
echo "5. Copy these two keys:"
echo "   - Publishable Key (starts with pk_test_)"
echo "   - Secret Key (starts with sk_test_)"
echo ""
echo ""
echo "📝 STEP 2: Add Keys to Vercel"
echo "------------------------------"
echo ""
echo "Option A: Via Web (Recommended)"
echo "1. Open: https://vercel.com/brian-kramer-dealershipai/dealership-ai-dashboard/settings/environment-variables"
echo "2. Click 'Add New'"
echo "3. Add variable 1:"
echo "   - Key: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY"
echo "   - Value: <paste your publishable key>"
echo "   - Environment: Production"
echo "4. Click 'Save'"
echo "5. Click 'Add New' again"
echo "6. Add variable 2:"
echo "   - Key: CLERK_SECRET_KEY"
echo "   - Value: <paste your secret key>"
echo "   - Environment: Production"
echo "7. Click 'Save'"
echo ""
echo "Option B: Via CLI (Interactive)"
echo "Run these commands:"
echo ""
echo "  npx vercel env add NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY production"
echo "  # Paste your publishable key when prompted"
echo ""
echo "  npx vercel env add CLERK_SECRET_KEY production"
echo "  # Paste your secret key when prompted"
echo ""
echo ""
echo "📝 STEP 3: Redeploy"
echo "-------------------"
echo "After adding keys, redeploy with:"
echo ""
echo "  npx vercel --prod"
echo ""
echo ""
echo "📝 STEP 4: Configure Clerk Redirects"
echo "-------------------------------------"
echo "1. Go to: https://dashboard.clerk.com"
echo "2. Select your app"
echo "3. Go to: Configure → URLs"
echo "4. Add to Allowed Origins:"
echo "   - https://dealership-ai-dashboard-brian-kramer-dealershipai.vercel.app"
echo "   - https://dealershipai.com (if you add custom domain)"
echo "5. Set redirect URLs:"
echo "   - After sign in: /dashboard"
echo "   - After sign up: /dashboard"
echo ""
echo ""
echo "📝 STEP 5: Test"
echo "---------------"
echo "1. Visit: https://dealership-ai-dashboard-brian-kramer-dealershipai.vercel.app"
echo "2. Click 'Sign Up'"
echo "3. Complete registration"
echo "4. Should redirect to /dashboard"
echo ""
echo ""
echo "✅ Setup complete!"
echo ""
echo "Next: Follow PRODUCTION_SETUP_GUIDE.md for full SaaS setup"
echo ""

