/**
 * Supabase Database Types
 * Generated from schema.sql
 */
export interface Database {
  public: {
    Tables: {
      dealerships: {
        Row: {
          id: string;
          name: string;
          domain: string;
          city: string | null;
          state: string | null;
          tier: 'FREE' | 'PRO' | 'ENTERPRISE';
          sessions_used: number;
          sessions_limit: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          domain: string;
          city?: string | null;
          state?: string | null;
          tier?: 'FREE' | 'PRO' | 'ENTERPRISE';
          sessions_used?: number;
          sessions_limit?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          domain?: string;
          city?: string | null;
          state?: string | null;
          tier?: 'FREE' | 'PRO' | 'ENTERPRISE';
          sessions_used?: number;
          sessions_limit?: number;
          created_at?: string;
          updated_at?: string;
        };
      };
      users: {;
        Row: {
          id: string;
          clerk_id: string;
          email: string;
          dealership_id: string;
          role: 'user' | 'admin' | 'enterprise_admin';
          created_at: string;
        };
        Insert: {
          id?: string;
          clerk_id: string;
          email: string;
          dealership_id: string;
          role?: 'user' | 'admin' | 'enterprise_admin';
          created_at?: string;
        };
        Update: {
          id?: string;
          clerk_id?: string;
          email?: string;
          dealership_id?: string;
          role?: 'user' | 'admin' | 'enterprise_admin';
          created_at?: string;
        };
      };
      qai_scores: {;
        Row: {
          id: string;
          dealership_id: string;
          qai_star_score: number;
          authority_velocity: number;
          oci_value: number;
          ai_visibility: number;
          zero_click_shield: number;
          ugc_health: number;
          geo_trust: number;
          sgp_integrity: number;
          piqr_score: number;
          hrp_score: number;
          vai_penalized: number;
          seo_score: number;
          aeo_score: number;
          geo_score: number;
          calculated_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          qai_star_score: number;
          authority_velocity: number;
          oci_value: number;
          ai_visibility: number;
          zero_click_shield: number;
          ugc_health: number;
          geo_trust: number;
          sgp_integrity: number;
          piqr_score?: number;
          hrp_score?: number;
          vai_penalized: number;
          seo_score: number;
          aeo_score: number;
          geo_score: number;
          calculated_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          qai_star_score?: number;
          authority_velocity?: number;
          oci_value?: number;
          ai_visibility?: number;
          zero_click_shield?: number;
          ugc_health?: number;
          geo_trust?: number;
          sgp_integrity?: number;
          piqr_score?: number;
          hrp_score?: number;
          vai_penalized?: number;
          seo_score?: number;
          aeo_score?: number;
          geo_score?: number;
          calculated_at?: string;
        };
      };
      eeat_scores: {;
        Row: {
          id: string;
          dealership_id: string;
          experience: number;
          expertise: number;
          authoritativeness: number;
          trustworthiness: number;
          page_performance_index: number;
          structured_discoverability_index: number;
          local_surface_index: number;
          trust_authority_score: number;
          answer_share: number;
          audience_integrity_score: number;
          calculated_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          experience: number;
          expertise: number;
          authoritativeness: number;
          trustworthiness: number;
          page_performance_index: number;
          structured_discoverability_index: number;
          local_surface_index: number;
          trust_authority_score: number;
          answer_share: number;
          audience_integrity_score: number;
          calculated_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          experience?: number;
          expertise?: number;
          authoritativeness?: number;
          trustworthiness?: number;
          page_performance_index?: number;
          structured_discoverability_index?: number;
          local_surface_index?: number;
          trust_authority_score?: number;
          answer_share?: number;
          audience_integrity_score?: number;
          calculated_at?: string;
        };
      };
      ai_platform_scores: {;
        Row: {
          id: string;
          dealership_id: string;
          platform: 'chatgpt' | 'claude' | 'perplexity' | 'gemini' | 'copilot' | 'grok';
          visibility_score: number;
          mentions: number;
          sentiment: 'positive' | 'neutral' | 'negative';
          rank: number | null;
          market_share: number;
          measured_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          platform: 'chatgpt' | 'claude' | 'perplexity' | 'gemini' | 'copilot' | 'grok';
          visibility_score: number;
          mentions?: number;
          sentiment?: 'positive' | 'neutral' | 'negative';
          rank?: number | null;
          market_share: number;
          measured_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          platform?: 'chatgpt' | 'claude' | 'perplexity' | 'gemini' | 'copilot' | 'grok';
          visibility_score?: number;
          mentions?: number;
          sentiment?: 'positive' | 'neutral' | 'negative';
          rank?: number | null;
          market_share?: number;
          measured_at?: string;
        };
      };
      competitors: {;
        Row: {
          id: string;
          dealership_id: string;
          name: string;
          domain: string | null;
          city: string | null;
          rank: number;
          qai_score: number;
          score_change: number;
          gap: number;
          weaknesses: string[];
          updated_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          name: string;
          domain?: string | null;
          city?: string | null;
          rank: number;
          qai_score: number;
          score_change: number;
          gap: number;
          weaknesses: string[];
          updated_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          name?: string;
          domain?: string | null;
          city?: string | null;
          rank?: number;
          qai_score?: number;
          score_change?: number;
          gap?: number;
          weaknesses?: string[];
          updated_at?: string;
        };
      };
      quick_wins: {;
        Row: {
          id: string;
          dealership_id: string;
          title: string;
          description: string | null;
          category: 'schema' | 'reviews' | 'citations' | 'content' | 'seo' | 'aeo' | 'geo';
          impact_points: number;
          revenue_monthly: number;
          effort: 'easy' | 'medium' | 'hard';
          time_to_fix: string;
          status: 'critical' | 'high' | 'medium' | 'low';
          completed: boolean;
          completed_at: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          title: string;
          description?: string | null;
          category: 'schema' | 'reviews' | 'citations' | 'content' | 'seo' | 'aeo' | 'geo';
          impact_points: number;
          revenue_monthly: number;
          effort: 'easy' | 'medium' | 'hard';
          time_to_fix: string;
          status: 'critical' | 'high' | 'medium' | 'low';
          completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          title?: string;
          description?: string | null;
          category?: 'schema' | 'reviews' | 'citations' | 'content' | 'seo' | 'aeo' | 'geo';
          impact_points?: number;
          revenue_monthly?: number;
          effort?: 'easy' | 'medium' | 'hard';
          time_to_fix?: string;
          status?: 'critical' | 'high' | 'medium' | 'low';
          completed?: boolean;
          completed_at?: string | null;
          created_at?: string;
        };
      };
      mystery_shops: {;
        Row: {
          id: string;
          dealership_id: string;
          shop_type: 'email' | 'chat' | 'phone' | 'form';
          query_text: string | null;
          response_text: string | null;
          response_time_score: number;
          personalization_score: number;
          transparency_score: number;
          followup_score: number;
          professionalism_score: number;
          overall_score: number;
          conducted_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          shop_type: 'email' | 'chat' | 'phone' | 'form';
          query_text?: string | null;
          response_text?: string | null;
          response_time_score: number;
          personalization_score: number;
          transparency_score: number;
          followup_score: number;
          professionalism_score: number;
          overall_score: number;
          conducted_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          shop_type?: 'email' | 'chat' | 'phone' | 'form';
          query_text?: string | null;
          response_text?: string | null;
          response_time_score?: number;
          personalization_score?: number;
          transparency_score?: number;
          followup_score?: number;
          professionalism_score?: number;
          overall_score?: number;
          conducted_at?: string;
        };
      };
      activity_log: {;
        Row: {
          id: string;
          dealership_id: string;
          user_id: string;
          action: string;
          target: string | null;
          delta: string | null;
          created_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          user_id: string;
          action: string;
          target?: string | null;
          delta?: string | null;
          created_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          user_id?: string;
          action?: string;
          target?: string | null;
          delta?: string | null;
          created_at?: string;
        };
      };
      geo_pools: {;
        Row: {
          id: string;
          city: string;
          state: string;
          pooled_scores: any // JSONB;
          dealer_count: number;
          expires_at: string;
          created_at: string;
        };
        Insert: {
          id?: string;
          city: string;
          state: string;
          pooled_scores: any // JSONB;
          dealer_count?: number;
          expires_at: string;
          created_at?: string;
        };
        Update: {
          id?: string;
          city?: string;
          state?: string;
          pooled_scores?: any // JSONB;
          dealer_count?: number;
          expires_at?: string;
          created_at?: string;
        };
      };
      session_logs: {;
        Row: {
          id: string;
          dealership_id: string;
          user_id: string;
          action_type: 'score_refresh' | 'competitor_analysis' | 'report_export' | 'mystery_shop' | 'ai_chat_query' | 'schema_generate' | 'review_draft';
          created_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          user_id: string;
          action_type: 'score_refresh' | 'competitor_analysis' | 'report_export' | 'mystery_shop' | 'ai_chat_query' | 'schema_generate' | 'review_draft';
          created_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          user_id?: string;
          action_type?: 'score_refresh' | 'competitor_analysis' | 'report_export' | 'mystery_shop' | 'ai_chat_query' | 'schema_generate' | 'review_draft';
          created_at?: string;
        };
      };
      vco_predictions: {;
        Row: {
          id: string;
          dealership_id: string;
          vdp_id: string | null;
          vdp_features: any // JSONB;
          conversion_probability: number;
          shap_values: any // JSONB;
          recommended_actions: any // JSONB;
          calculated_at: string;
        };
        Insert: {
          id?: string;
          dealership_id: string;
          vdp_id?: string | null;
          vdp_features?: any // JSONB;
          conversion_probability: number;
          shap_values?: any // JSONB;
          recommended_actions?: any // JSONB;
          calculated_at?: string;
        };
        Update: {
          id?: string;
          dealership_id?: string;
          vdp_id?: string | null;
          vdp_features?: any // JSONB;
          conversion_probability?: number;
          shap_values?: any // JSONB;
          recommended_actions?: any // JSONB;
          calculated_at?: string;
        };
      };
    };
    Views: {;
      [_ in never]: never;
    };
    Functions: {;
      [_ in never]: never;
    };
    };
    Enums: {;
      [_ in never]: never;
    };
    };
  };
};