/**
 * PDF Report Generator
 * 
 * Generates white-label PDF reports from dashboard data
 */

import { jsPDF } from 'jspdf';

export interface DashboardData {
  dealershipName: string;
  trustScore: number;
  scoreDelta: number;
  pillars: {
    seo: number;
    aeo: number;
    geo: number;
    qai: number;
  };
  metrics?: {
    vai: number;
    piqr: number;
    hrp: number;
    qai: number;
  };
  revenueAtRisk?: number;
  trends?: Record<string, number>;
  period: {
    startDate: string;
    endDate: string;
  };
}

export interface Branding {
  logo?: string;
  primaryColor: string;
  companyName: string;
}

/**
 * Generate white-label PDF report
 */
export async function generateWhiteLabelReport(
  dashboardData: DashboardData,
  branding: Branding
): Promise<void> {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // Helper to convert hex to RGB
  const hexToRgb = (hex: string) => {
    const result = /^#?([a-f\d]{2})([a-f\d]{2})([a-f\d]{2})$/i.exec(hex);
    return result ? {
      r: parseInt(result[1], 16),
      g: parseInt(result[2], 16),
      b: parseInt(result[3], 16)
    } : { r: 0, g: 0, b: 0 };
  };

  const rgb = hexToRgb(branding.primaryColor);

  // Cover page
  pdf.setFillColor(rgb.r, rgb.g, rgb.b);
  pdf.rect(0, 0, pageWidth, pageHeight, 'F');

  // Add logo (if provided)
  if (branding.logo) {
    try {
      pdf.addImage(branding.logo, 'PNG', pageWidth / 2 - 25, 80, 50, 20);
    } catch (e) {
      console.warn('Failed to add logo:', e);
    }
  }

  // Title
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(24);
  pdf.text('AI Visibility Intelligence Report', pageWidth / 2, 120, { align: 'center' });

  // Dealership name
  pdf.setFontSize(18);
  pdf.text(dashboardData.dealershipName, pageWidth / 2, 140, { align: 'center' });

  // Date
  pdf.setFontSize(12);
  pdf.text(
    `${dashboardData.period.startDate} - ${dashboardData.period.endDate}`,
    pageWidth / 2,
    150,
    { align: 'center' }
  );

  // New page - Executive Summary
  pdf.addPage();
  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(20);
  pdf.text('Executive Summary', 20, 20);

  // Trust Score
  pdf.setFontSize(14);
  pdf.text(`Trust Score: ${dashboardData.trustScore}/100`, 20, 40);

  // Score Delta
  pdf.setFontSize(12);
  const deltaColor = dashboardData.scoreDelta >= 0 ? [0, 150, 0] : [200, 0, 0];
  pdf.setTextColor(deltaColor[0], deltaColor[1], deltaColor[2]);
  pdf.text(
    `Change: ${dashboardData.scoreDelta > 0 ? '+' : ''}${dashboardData.scoreDelta} points`,
    20,
    50
  );
  pdf.setTextColor(0, 0, 0);

  // Pillars
  pdf.setFontSize(14);
  pdf.text('Pillar Scores', 20, 70);

  pdf.setFontSize(12);
  let yPos = 85;
  Object.entries(dashboardData.pillars).forEach(([key, value]) => {
    pdf.text(`${key.toUpperCase()}: ${value}/100`, 25, yPos);
    yPos += 10;
  });

  // Metrics
  if (dashboardData.metrics) {
    pdf.setFontSize(14);
    pdf.text('Key Metrics', 20, yPos + 10);

    pdf.setFontSize(12);
    yPos += 25;
    Object.entries(dashboardData.metrics).forEach(([key, value]) => {
      pdf.text(`${key.toUpperCase()}: ${value.toFixed(1)}`, 25, yPos);
      yPos += 10;
    });
  }

  // Revenue at Risk
  if (dashboardData.revenueAtRisk) {
    pdf.setFontSize(14);
    pdf.text('Financial Impact', 20, yPos + 10);

    pdf.setFontSize(12);
    pdf.setTextColor(200, 0, 0);
    pdf.text(
      `Revenue at Risk: $${dashboardData.revenueAtRisk.toLocaleString()}`,
      25,
      yPos + 25
    );
    pdf.setTextColor(0, 0, 0);
  }

  // Footer on all pages
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(128, 128, 128);
    pdf.text(
      `Generated by ${branding.companyName} - Page ${i} of ${totalPages}`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
    pdf.text(
      `Report Period: ${dashboardData.period.startDate} to ${dashboardData.period.endDate}`,
      pageWidth / 2,
      pageHeight - 5,
      { align: 'center' }
    );
  }

  // Download
  pdf.save(`${dashboardData.dealershipName}-AI-Report-${Date.now()}.pdf`);
}

/**
 * Generate shareable snapshot (lightweight version)
 */
export function generateShareableSnapshot(data: DashboardData): string {
  // Return base64 encoded image or data URL
  // This is a placeholder - in production, use html2canvas
  return JSON.stringify({
    dealershipName: data.dealershipName,
    trustScore: data.trustScore,
    generatedAt: new Date().toISOString()
  });
}

