#!/bin/bash
# Non-interactive version - shows what needs to be done

set -e

echo "🎯 DealershipAI Dashboard - Setup Guide"
echo "=========================================="
echo ""
echo "Since this requires interactive input, please run these commands in your terminal:"
echo ""
echo "═══════════════════════════════════════"
echo "STEP 1: Environment Variables"
echo "═══════════════════════════════════════"
echo "Run: ./scripts/setup-env.sh"
echo ""
echo "This will prompt you for:"
echo "  - Clerk keys (from https://dashboard.clerk.com)"
echo "  - Supabase keys (from https://supabase.com/dashboard)"
echo "  - Upstash Redis keys (from https://console.upstash.com)"
echo "  - Your production domain"
echo ""
echo "═══════════════════════════════════════"
echo "STEP 2: Supabase Migrations"
echo "═══════════════════════════════════════"
echo "Run: ./scripts/setup-supabase.sh"
echo ""
echo "This will:"
echo "  - Link to your Supabase project"
echo "  - Apply database migrations"
echo ""
echo "═══════════════════════════════════════"
echo "STEP 3: Clerk Configuration (Manual)"
echo "═══════════════════════════════════════"
echo "1. Go to https://dashboard.clerk.com"
echo "2. Select your application"
echo "3. Settings → Domains → Add your production domain"
echo "4. Settings → Paths → Verify redirect URLs"
echo ""
echo "═══════════════════════════════════════"
echo "STEP 4: Deploy"
echo "═══════════════════════════════════════"
echo "Run: ./scripts/deploy.sh"
echo ""
echo "This will:"
echo "  - Check all prerequisites"
echo "  - Build the project"
echo "  - Deploy to Vercel production"
echo ""
echo "═══════════════════════════════════════"
echo "OR: Run All Steps at Once"
echo "═══════════════════════════════════════"
echo "In your terminal, run:"
echo "  ./scripts/setup-all.sh"
echo ""
echo "This will guide you through all steps interactively."
echo ""

